spring:
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/changelog-master.xml'
    default-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/socially'
    username: socially
    password: socially
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: '/api-docs'
application:
  environment:
    testing-endpoints-enabled: false
  jwt:
    prefix: Bearer
    secret: ZDUyNjc5MTMtNGE5Yi00OTNjLWJjNmUtY2IxMzUzYTllNzU5LTA2ZjJmNmMyLTU4NDQtNDYzMi04Mjk2LTg4OWZkNTU3MTlkNA==
    access-token-expiration-in-millis: 300000 # 5 minutes in millis
    refresh-token-expiration-in-millis: 1209600000 # 14 days in millis