spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
application:
  environment:
    testing-endpoints-enabled: false
  jwt:
    prefix: Bearer
    secret: ZDUyNjc5MTMtNGE5Yi00OTNjLWJjNmUtY2IxMzUzYTllNzU5LTA2ZjJmNmMyLTU4NDQtNDYzMi04Mjk2LTg4OWZkNTU3MTlkNA==
    access-token-expiration-in-millis: 300000 # 5 minutes in millis
    refresh-token-expiration-in-millis: 1209600000 # 14 days in millis