spring:
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/changelog-master.xml'
    default-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/socially'
    username: socially
    password: socially
springdoc:
  api-docs:
    path: '/api-docs'