spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
application:
  environment:
    testing-endpoints-enabled: true
  jwt:
    prefix: Bearer
    secret: ZDUyNjc5MTMtNGE5Yi00OTNjLWJjNmUtY2IxMzUzYTllNzU5LTA2ZjJmNmMyLTU4NDQtNDYzMi04Mjk2LTg4OWZkNTU3MTlkNA==
    access-token-expiration-in-millis: 10000 # 10 seconds in millis
    refresh-token-expiration-in-millis: 120000 # 2 minutes in millis